version: "3.8"

services:
  tooncrafter:
    container_name: tooncrafter
    image: maximofn/tooncrafter:1.0.1
    build: .
    runtime: nvidia
    network_mode: "host"
    volumes:
      - ./hub:/root/.cache/huggingface/hub
    tty: true
    stdin_open: true
