FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends git git-lfs python3 python3-pip \
    && apt-get install -y --no-install-recommends libgl1-mesa-glx libglib2.0-0 \
    && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
    && git lfs install \
    && rm cuda-keyring_1.0-1_all.deb \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN git clone --depth 1 https://huggingface.co/spaces/Doubiiu/tooncrafter \
    && cd tooncrafter && pip3 install --no-cache-dir -r requirements.txt

RUN pip3 install --no-cache-dir spaces accelerate

RUN sed -i 's/model = model\.cuda()/model = model\.half()\.cuda()/' /tooncrafter/scripts/gradio/i2v_test_application.py

WORKDIR /tooncrafter